apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: gc-ttl
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlStrategy:
    secondsAfterSuccess: 5
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
